spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_schema
    username: root
    password: Pietro2004
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      